import type { Request, Response, NextFunction } from 'express';
import { getAdminAuth, getTargetFirebaseProjectId } from '../services/firebaseAdmin';

/**
 * requireAuth Middleware
 *
 * Enforces the server-verified identity and authorization boundary.
 * 1. Reads the Authorization: Bearer <Firebase ID Token> header.
 * 2. Cryptographically validates signature, expiration, and audience via Firebase Admin SDK.
 * 3. Binds the resulting authenticated identity identifier (UID) to req.user.
 * 4. Strictly forbids and rejects any client-supplied identity fields (uid, userId, ownerUid) in body or query.
 */
export const requireAuth = async (
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> => {
  const authHeader = req.headers.authorization;

  // 1. Missing Authorization header
  if (!authHeader) {
    res.status(401).json({
      error: 'Authentication required. Missing Authorization Bearer header.',
      code: 'AUTH_REQUIRED',
    });
    return;
  }

  // 2. Malformed Authorization header (missing Bearer prefix)
  if (!authHeader.startsWith('Bearer ')) {
    res.status(401).json({
      error: 'Authentication required. Missing or malformed Authorization Bearer header.',
      code: 'AUTH_REQUIRED',
    });
    return;
  }

  const idToken = authHeader.slice('Bearer '.length).trim();
  if (!idToken) {
    res.status(401).json({
      error: 'Invalid token format. Bearer token is empty.',
      code: 'INVALID_TOKEN_FORMAT',
    });
    return;
  }

  // 3. Reject any request attempting to pass client-supplied identity parameters (Anti-UID Tampering)
  const hasBodyUid =
    req.body &&
    typeof req.body === 'object' &&
    ('uid' in req.body || 'userId' in req.body || 'ownerUid' in req.body);
  const hasQueryUid =
    req.query &&
    typeof req.query === 'object' &&
    ('uid' in req.query || 'userId' in req.query || 'ownerUid' in req.query);

  if (hasBodyUid || hasQueryUid) {
    res.status(400).json({
      error: 'Client-supplied identity fields (uid, userId) are strictly forbidden. The authenticated identity is derived exclusively from server-verified tokens.',
      code: 'UNEXPECTED_IDENTITY_FIELD',
    });
    return;
  }

  const targetProjectId = getTargetFirebaseProjectId();

  // 4. Safe temporary diagnostics (Never logs tokens, keys, or personal contents)
  if (process.env.NODE_ENV !== 'production' || process.env.DEBUG_AUTH) {
    console.log('[AUTH_DIAGNOSTIC] Verification attempt:', {
      path: req.path,
      method: req.method,
      hasAuthHeader: true,
      hasBearerPrefix: true,
      tokenLength: idToken.length,
      targetProjectId,
    });
  }

  let adminAuth;
  try {
    adminAuth = getAdminAuth();
  } catch (initErr: any) {
    console.error('[AUTH_DIAGNOSTIC] Firebase Admin initialization failure:', {
      category: 'ADMIN_INIT_FAILURE',
      targetProjectId,
      error: initErr?.message,
    });
    res.status(500).json({
      error: 'Authentication service temporarily unavailable.',
      code: 'AUTH_SERVICE_UNAVAILABLE',
    });
    return;
  }

  try {
    const decodedToken = await adminAuth.verifyIdToken(idToken);

    if (!decodedToken || !decodedToken.uid) {
      res.status(401).json({
        error: 'Invalid or empty identity token claims.',
        code: 'INVALID_IDENTITY_TOKEN',
      });
      return;
    }

    // Attach authenticated identity exclusively from the server-verified token
    req.user = decodedToken;

    next();
  } catch (err: any) {
    // In non-production preview/dev mode ONLY, safely recognize demo tokens generated by preview fallback
    if (process.env.NODE_ENV !== 'production' && idToken.startsWith('demo_token_')) {
      const demoUid = idToken.slice('demo_token_'.length).trim();
      if (demoUid && /^[a-zA-Z0-9_\-]+$/.test(demoUid) && demoUid.length <= 128) {
        req.user = {
          uid: demoUid,
          email: 'demo@journal.internal',
          name: 'Demo User',
        } as any;
        next();
        return;
      }
    }

    const errCode = err?.code || 'UNKNOWN';
    const errMsg = typeof err?.message === 'string' ? err.message : '';

    let responseCode = 'AUTH_VERIFICATION_FAILED';
    let responseError = 'Authentication verification failed.';

    if (errCode === 'auth/id-token-expired') {
      responseCode = 'TOKEN_EXPIRED';
      responseError = 'Session expired. Please refresh your credentials.';
    } else if (
      errMsg.includes('audience') ||
      errMsg.includes('incorrect "aud"') ||
      errMsg.includes('project') ||
      errCode === 'auth/project-id-mismatch'
    ) {
      responseCode = 'PROJECT_MISMATCH';
      responseError = 'Authentication failed due to project identity mismatch.';
    } else if (errCode === 'auth/id-token-revoked') {
      responseCode = 'TOKEN_REVOKED';
      responseError = 'Authentication credentials have been revoked. Please sign in again.';
    }

    console.warn('[AUTH_DIAGNOSTIC] Token verification failure:', {
      path: req.path,
      category: responseCode,
      firebaseErrorCode: errCode,
      targetProjectId,
      tokenLength: idToken.length,
    });

    res.status(401).json({
      error: responseError,
      code: responseCode,
    });
  }
};
